apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.17.10
        ports:
        - containerPort: 5044
          name: beats
        - containerPort: 5000
          name: tcp
        env:
        - name: LS_JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/pipeline/
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: logstash-config